version: "3.1"

services:
  db:
    image: "postgres:alpine"
    environment:
      - POSTGRES_USER=chatapp
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=chatapp
    ports:
      - "5432"

  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"

  web:
    build: .
    restart: unless-stopped
    tty: true
    stdin_open: true
    ports:
      - "8000:8000"
    volumes:
      - ./:/home/user/app/
    depends_on:
      - db
      - redis
    dns:
      - 8.8.8.8
